### ISSUE TITLE
CloudEventBuilder constructor that fills some default values

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#164]
Create a method to start building a new CloudEvent filling some default values like:

* `id`: using UUID
* `time`: current time
* `source`: current hostname

**Comment by bsideup** [comment]
I don't think this is a good idea. My 2c:

Being an explicit about the required attributes make the users think about them. e.g. if you already have an id a hands, it would be better to use it for he correlation.

Also, there are hidden implications like:
- UUID is blocking by default. Some systems may not want to have a blocking code in their code, and implicit blocking code isn't a good thing
- getting a hostname is known to be a long operation on some systems (like the infamous Mac OS X hostname issue). It would be a surprise to learn that the app starts 5 second slower just because an SDK for in-memory representation of something tries to get a hostname :D 
- Even the current time - it discourages the testability of the code ("oh, nice, I don't need to think about providing the time supplier!") and may cause issues with retries - since it is hidden, an inexperienced user may not know about it and will produce a logically new event on each retry.

**Comment by slinkydeveloper** [comment]
So first of all, this method to start with default values is definitely optional, but TBH I didn't thought about the blocking nature of UUID nor hostname. And yes it's not a good idea to have such method blocking, because then people will abuse of it... My initial idea was:

- id: I would love to have an automatic id generation, and UUID comes to my mind for this.
- source: hostname sounds the more reasonable, but we could have just a default value like "http://github.com/cloudevents/sdk-java". But that sounds pretty weird...
- time: to me the current time seems reasonable, and of course i don't expect that in tests you use such "default builder" method that setup the timestamp to now.

So for now i wish to keep the discussion here and listen to other inputs, and we should also consider that #163 already vastly simplifies the building, using some default values... Maybe we can just say to the user "create your own builder template if you want default values"

**Comment by slinkydeveloper** [comment]
I'm gonna close it for the moment, if somebody is interested in this one, please reopen it
