### ISSUE TITLE
Question: How to showcase support from http4k

### ISSUE THREAD

**Issue by daviddenton** [cloudevents/sdk-java#344]
We've just added support for the CE spec in [http4k](https://http4k.org) and were wondering how we could feature this support in this SDK repo. The integration itself was pretty trivial - it was great that there wasn't much to do for us to integrate cleanly with your SDK and JSON format so sending and consuming CloudEvents is simple in a normal http4k app. You can see from the [example](https://www.http4k.org/guide/modules/cloud_events/) that we managed to hide the machinery and mostly just expose the `CloudEvent` and `CloudEventData` types.

Anyway, because it's all written in Kotlin, and we've got a [monorepo](https://github.com/http4k/http4k) for all http4k assets (with a single BOM), we like keeping the various lib integration code close to the rest - which is why we're housed it over there.

For this repo, we could add just a mention with a link to the main http4k repo example on the our site, or we can add a full example showing the integration at work in this repo. The only concern there is that the example would be Kotlin, so this might be a hurdle.

We are happy to do the work for this - just need a steer from your team as to if this is something you'd consider for this repo. 😄

**Comment by slinkydeveloper** [comment]
Hi! I'm happy to see the sdk used in http4k, I cannot wait to see more feedback coming in! 

About showcasing it, how about adding a link of the docs you posted here to https://github.com/cloudevents/sdk-java#used-by and https://github.com/cloudevents/sdk-java#status and https://github.com/cloudevents/sdk-java/blob/master/docs/index.md#supported-features? I'm not sure an example in this repo is a good idea, since we might not be able to maintain it in the long run and it might become obsolete soon.

**Comment by daviddenton** [comment]
After some wrestling with markdown, [the PR](https://github.com/cloudevents/sdk-java/pull/345) is ready to go. 

Thanks for your help @slinkydeveloper  😄
