### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by robp94** [cloudevents/sdk-java#552]
### Discussed in https://github.com/cloudevents/sdk-java/discussions/548

<div type='discussions-op-text'>

<sup>Originally posted by **robp94** April 12, 2023</sup>
We use quarkus with `cloudevents-http-restful-ws.` Quarkus soon releases 3.0 with the switch from javax to jakarta. So we would need `cloudevents-http-restful-ws-jakarta`. But it seems there is no release for this yet. </div>

**Comment by pierDipi** [comment]
Hi @robp94, there is no current plan for the next release, however, for your case, we can think about backporting https://github.com/cloudevents/sdk-java/commit/f08a099ed9728d1c98380f95496c0b9cd87adfa0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8 to the 2.4 branch if there are no breaking changes and release a patch release 

That would be much faster/easier because we're currently planning to release a 3.0 major release and I'd like to discuss some big features (like #542) and whether they might bring breaking changes or not to the APIs to then require another major release.

**Comment by robp94** [comment]
That would be very nice :)

**Comment by robp94** [comment]
@pierDipi do you have any time frame for a patch release? Quarkus 3.0 released this week.

**Comment by pierDipi** [comment]
No unfortunately, contributions are really welcome!

we need to:
- assess whether https://github.com/cloudevents/sdk-java/commit/f08a099ed9728d1c98380f95496c0b9cd87adfa0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8 is a backward compatible change
  - if it's not:
    - we need to either find a way to make a similar commit to 2.4 that is backward compatible
    - we have no choices other releasing 3.0 (no ETA on it still)
  - if it is, proposing a backport commit to the 2.4 branch

**Comment by robp94** [comment]
@pierDipi I made a pr could you have a look what is still missing or if it could get merged?
https://github.com/cloudevents/sdk-java/pull/557

**Comment by pierDipi** [comment]
Let's see how the 2.5 branch build goes: https://github.com/cloudevents/sdk-java/actions/runs/4981686650/jobs/8916270306

**Comment by pierDipi** [comment]
@robp94 let us know if that works for you
